name: CICD

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
       uses: actions/checkout@v3
      
      -name: Login to Docker Hub
       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      -name: Build Docker Image
       run: docker build -t brotin003/experiencezone .
      
      -name: Publish Image to Docker Hub
       run: docker push brotin003/experiencezone:latest

  deploy:
    depends-on: build
    runs-on: aws-ec2
    steps:
      -name: Pull Image from Docker Hub
       run: docker pull brotin003/experiencezone:latest

      -name: Delete Old container
       run: docker rm -f reactcontainer
      
      -name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactcontainer brotin003/experiencezone